# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.action_New = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("audioeditor/ui/resources/file-new.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New.setIcon(icon)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Save_2 = QtWidgets.QAction(MainWindow)
        self.action_Save_2.setObjectName("action_Save_2")
        self.actionS_wap = QtWidgets.QAction(MainWindow)
        self.actionS_wap.setObjectName("actionS_wap")
        self.action_Delete = QtWidgets.QAction(MainWindow)
        self.action_Delete.setObjectName("action_Delete")
        self.actionChange_Volume = QtWidgets.QAction(MainWindow)
        self.actionChange_Volume.setObjectName("actionChange_Volume")
        self.actionChange_S_peed = QtWidgets.QAction(MainWindow)
        self.actionChange_S_peed.setObjectName("actionChange_S_peed")
        self.actionFade_In = QtWidgets.QAction(MainWindow)
        self.actionFade_In.setObjectName("actionFade_In")
        self.actionFade_Out = QtWidgets.QAction(MainWindow)
        self.actionFade_Out.setObjectName("actionFade_Out")
        self.actionChange_Pitc_h = QtWidgets.QAction(MainWindow)
        self.actionChange_Pitc_h.setObjectName("actionChange_Pitc_h")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Exit)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionS_wap)
        self.menuEdit.addAction(self.action_Delete)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionChange_Pitc_h)
        self.menuEdit.addAction(self.actionChange_Volume)
        self.menuEdit.addAction(self.actionChange_S_peed)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFade_In)
        self.menuEdit.addAction(self.actionFade_Out)
        self.menuEdit.addSeparator()
        self.menuAbout.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionS_wap)
        self.toolBar.addAction(self.action_Delete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionChange_Pitc_h)
        self.toolBar.addAction(self.actionChange_Volume)
        self.toolBar.addAction(self.actionChange_S_peed)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFade_In)
        self.toolBar.addAction(self.actionFade_Out)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_3)
        self.toolBar.addAction(self.action_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AudioEditor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_New.setText(_translate("MainWindow", "&New"))
        self.action_New.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_Recent.setText(
            _translate("MainWindow", "Open &Recent")
        )
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.action_Save_2.setText(_translate("MainWindow", "&Save"))
        self.actionS_wap.setText(_translate("MainWindow", "S&wap"))
        self.action_Delete.setText(_translate("MainWindow", "&Delete"))
        self.actionChange_Volume.setText(
            _translate("MainWindow", "Change &Volume"))
        self.actionChange_S_peed.setText(
            _translate("MainWindow", "Change S&peed"))
        self.actionFade_In.setText(_translate("MainWindow", "Fade &In"))
        self.actionFade_Out.setText(_translate("MainWindow", "Fade &Out"))
        self.actionChange_Pitc_h.setText(
            _translate("MainWindow", "Change Pitc&h"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.action_2.setText(_translate("MainWindow", "->"))
        self.action_3.setText(_translate("MainWindow", "<-"))
